---
apiVersion: v1
kind: Namespace
metadata:
  name: dynamo-qwen
---
# etcd for service discovery
apiVersion: v1
kind: Pod
metadata:
  name: etcd
  namespace: dynamo-qwen
  labels:
    app: etcd
spec:
  restartPolicy: Always
  containers:
  - name: etcd
    image: bitnamilegacy/etcd:3.6.1
    env:
    - name: ALLOW_NONE_AUTHENTICATION
      value: "yes"
    ports:
    - containerPort: 2379
      name: client
    - containerPort: 2380
      name: peer
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
  namespace: dynamo-qwen
spec:
  selector:
    app: etcd
  ports:
  - name: client
    port: 2379
    targetPort: 2379
  - name: peer
    port: 2380
    targetPort: 2380
---
# NATS with JetStream for event plane
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: dynamo-qwen
data:
  nats-server.conf: |
    max_payload: 15728640
    jetstream: {}
    http_port: 8222
---
apiVersion: v1
kind: Pod
metadata:
  name: nats
  namespace: dynamo-qwen
  labels:
    app: nats
spec:
  restartPolicy: Always
  containers:
  - name: nats
    image: nats:2.11.4
    args: ["-c", "/etc/nats/nats-server.conf"]
    ports:
    - containerPort: 4222
      name: client
    - containerPort: 8222
      name: monitoring
    volumeMounts:
    - name: config
      mountPath: /etc/nats
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
  volumes:
  - name: config
    configMap:
      name: nats-config
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: dynamo-qwen
spec:
  selector:
    app: nats
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: monitoring
    port: 8222
    targetPort: 8222
