# KVBM Worker: G2 (CPU 20GB) + G3 (Local Disk 10GB on /tmp)
# No 3FS sidecar, uses local NVMe for disk cache
apiVersion: v1
kind: Pod
metadata:
  name: dynamo-worker
  namespace: dynamo-qwen
  labels:
    app: dynamo-worker
spec:
  restartPolicy: Never
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  securityContext:
    runAsUser: 0
  nodeSelector:
    kubernetes.io/hostname: p02-r02-cp17
  containers:
  - name: worker
    image: nvcr.io/nvidia/ai-dynamo/tensorrtllm-runtime:0.9.0
    command: ["/bin/bash", "-c"]
    args:
    - |
      set -e
      # Create local disk cache directory
      mkdir -p /tmp/kvbm_disk_cache

      echo "Starting TRT-LLM worker with KVBM (local disk)..."
      exec python3 -m dynamo.trtllm \
        --model-path /data/huggingface/hub/models--Qwen--Qwen3-8B/snapshots/b968826d9c46dd6066d109eabc6255188de91218 \
        --served-model-name Qwen/Qwen3-8B \
        --modality text \
        --extra-engine-args /etc/dynamo/agg.yaml \
        --connector kvbm
    ports:
    - containerPort: 8081
      name: metrics
      hostPort: 8081
    env:
    - name: ETCD_ENDPOINTS
      value: "172.29.22.14:2379,172.29.202.242:2379,172.29.134.203:2379"
    - name: NATS_SERVER
      value: "nats://172.29.182.124:4222"
    - name: DYN_SYSTEM_PORT
      value: "8081"
    - name: HF_HOME
      value: /data/huggingface
    - name: HF_HUB_OFFLINE
      value: "1"
    - name: TRANSFORMERS_OFFLINE
      value: "1"
    - name: DYN_LOG
      value: "info"
    - name: DYNAMO_MODEL_NAMESPACE
      value: "qwen"
    # KVBM Configuration
    - name: DYN_KVBM_CPU_CACHE_GB
      value: "20"
    - name: DYN_KVBM_DISK_CACHE_GB
      value: "10"
    - name: DYN_KVBM_DISK_CACHE_DIR
      value: "/tmp/kvbm_disk_cache"
    - name: DYN_KVBM_METRICS
      value: "true"
    resources:
      requests:
        cpu: "4"
        memory: "32Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "16"
        memory: "64Gi"
        nvidia.com/gpu: "1"
    volumeMounts:
    - name: hf-cache
      mountPath: /data/huggingface
    - name: shm
      mountPath: /dev/shm
    - name: engine-config
      mountPath: /etc/dynamo
  volumes:
  - name: hf-cache
    hostPath:
      path: /data/huggingface
      type: DirectoryOrCreate
  - name: shm
    emptyDir:
      medium: Memory
      sizeLimit: 16Gi
  - name: engine-config
    configMap:
      name: trtllm-engine-config
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
